swagger: "2.0"
paths:
  /anything:
    post:
      produces:
        - application/octet-stream
      consumes:
        - application/octet-stream
      responses:
        200:
          description: OK
